### ISSUE TITLE
Several typos in French translation

### ISSUE THREAD

**Issue by bouscram** [Polarrco/polarr_mac_windows_support#23]
Hi. There are several typos in the French translation (version 2.0.1):
- "_Ouvert Photos_" for "_Ouvrir Photos_"
- "_Photos ouvert_" for "_Photos ouvertes_"
- "_Histoire édition_" for "_Historique d'édition_"
- "_Ajustements Mocaux_" for "_Ajustements Locaux_"
- "_xouper_" for "_Couper_"
- in the parameters: "_Désactiver la résolution exportation complète_" for "_Désactiver l'exportation à pleine résolution_"
- in the Detail settings: _"Aigiiser"_ for _"Aiguiser"_

**Comment by bwang29** [comment]
Changes will be absorbed in 4.3.0 update. Thank you for the suggestions.
