### ISSUE TITLE
Image width doubled

### ISSUE THREAD

**Issue by kikaweb** [Polarrco/polarr_mac_windows_support#37]
This issue may be related to issue #36. Often when I open an image in Polarr it appears wider than it should be - I thing 'elongated' is the right word, sorry if my english is far from perfect. I never use full screen mode.
Anyway it happens frequently, I have this problem with 3 out of 5 photos, but I cannot replicate the problem. It happens with different pics - that is different ratio or size. 
I tried to reboot my Mac, but that didn't fix the problem. Also it is not a problem of how the image is visualized: if I save the image, it retains its wrong ratio. 
I'm working with OsX 10.11.6.

**Comment by ybnl2048** [comment]
Yop! Same issue as mine (#36). All in all, even if you don't use full screen, I feel there is something wrong with the image ratio. Btw it was on raw files coming from an Sony A7.

**Comment by kikaweb** [comment]
I've only used jpg images from different sources, but if the developer needs more data I can try with some raw files - I have a Pentax K-r.

**Comment by seanpkent** [comment]
@kikaweb @ybnl2048 could you upload one or more of the photos you are having this issue with? That would help me a lot in figuring out what the problem might be. Thanks!

**Comment by kikaweb** [comment]
Hi @seanpkent thanks for your reply. 
Please find my screenshot attached, and you can see [the original image here]. (https://unsplash.com/search/grape?photo=vGQ49l9I4EE). 

If you need any other detail, please ask. I'll be more than happy to provide any info useful for the debug. 
![polarr_screenshot-2016-10-03-19 31 26](https://cloud.githubusercontent.com/assets/1549617/19047037/71e62dae-89a0-11e6-9a00-053e532b55c8.jpg)

**Comment by seanpkent** [comment]
@kikaweb Sorry for the delayed reply, but this has been fixed in our last release. Thanks for the info!
