### ISSUE TITLE
[bug] colour profile problem with Photos extension

### ISSUE THREAD

**Issue by bouscram** [Polarrco/polarr_mac_windows_support#38]
When you open a picture with Photos extension, the colours are wrong. This is certainly a colour profile issue.
(Photos 2.0 on macOS Sierra / Polarr 3.1)

**Comment by bonka** [comment]
Same here. Running a photo through Polarr often times (not sure if it is every time, but I guess it's depending on how extensive the grade is) returns a image that looks very different than its Polarr counterpart. Most distinguishable is the saturation, that is always +2 in Photos.app.

**Comment by kpaddie** [comment]
Thank you so much to both of you for reporting on this issue. We are currently looking into it, and seeking a fix.

Best,

-Polarr team

**Comment by skrimaging** [comment]
Issue seems to happen even in the standalone app... I have imported a TIFF file to Polarr and color is all different.. 

when I open that Tiff file in Preview app macOS, colours are correct... in Polarr, saturation is washed out.

see screenshots:

![screen shot 2016-11-19 at 9 06 04 pm](https://cloud.githubusercontent.com/assets/16582747/20459882/ee10cd5c-ae9f-11e6-9dc5-0100900e2fd4.png)
![Uploading Screen Shot 2016-11-19 at 9.06.46 PM.png…]()
![screen shot 2016-11-19 at 9 19 43 pm](https://cloud.githubusercontent.com/assets/16582747/20459883/ee78fabc-ae9f-11e6-9039-6cea3c529f3c.png)

**Comment by bwang29** [comment]
We finally figured out this sRGB and RGB encoding issue, fixing soon early Jan....

**Comment by seanpkent** [comment]
Just to be clear - we've only fixed the issue where the exported image will look different than in Polarr. Safari's WebGL implementation doesn't handle color profiles, so images that have a profile other than sRGB will look different.

**Comment by bwang29** [comment]
Will be finally fixed soon.
