### ISSUE TITLE
[Feature Request] option to show/hide mask overlay

### ISSUE THREAD

**Issue by skrimaging** [Polarrco/polarr_mac_windows_support#44]
It would be great to see what part of the image the mask is affecting. 

maybe a button or keyboard shortcut to show and hide mask overlay could help.

the overlay could be red and provide helpful indication when brushing or colour masking to see exactly what will be affected...

to see an example of this implemented, download the free Snapseed app on iOS and set a selective adjustment point.. when you pich to grow or shrink the masking area, it provides visual clues to what part of image will be affected... helps a lot and would be a great feature for Polarr!

**Comment by bwang29** [comment]
This is added in 4.3.0 for macOS, and will hopefully be live before Friday. Already live in iOS. 

![image](https://user-images.githubusercontent.com/806199/32809739-ea0395dc-c94c-11e7-8b20-149f9e125c0f.png)
