### ISSUE TITLE
Pixelated Output After Saving Copy/Export

### ISSUE THREAD

**Issue by kimonostereo** [Polarrco/polarr_mac_windows_support#52]
When I save a copy of my edited photo, the copy has large blocks of pixelation embedded in the image.

Original image
![img_4930-small](https://cloud.githubusercontent.com/assets/175971/21858770/6a403d84-d7ce-11e6-9824-8eeeefee6e07.jpeg)

This is what it looks like in Polarr after editing
![screen shot 2017-01-11-small](https://cloud.githubusercontent.com/assets/175971/21858964/fff1c24e-d7ce-11e6-99cf-a40e0531fff6.jpg)

This is what it looks like after saving a copy or exporting
![img_4930-shift-small](https://cloud.githubusercontent.com/assets/175971/21858979/0a282bb8-d7cf-11e6-93f3-f9185ed9d2e5.jpeg)

There seems to be pixelation at the top and bottom. Here are some cropped closeups.
![img_4930-shift-crop2](https://cloud.githubusercontent.com/assets/175971/21859070/5bde153a-d7cf-11e6-961a-0033a5d09a14.jpeg)
![img_4930-shift-crop](https://cloud.githubusercontent.com/assets/175971/21859100/76dc68be-d7cf-11e6-8c6f-abe75c07ea40.jpeg)

I'm on a MacBook Pro Late 2016 w/ Touch Bar running Sierra 10.12.2.

Anyone else see this issue?

thanks,
\\scott\\

**Comment by seanpkent** [comment]
Hi Scott,
could you attach the full resolution image so I can test it out? It may be a problem with one of the image encoders. Did you export as a jpeg?

**Comment by kimonostereo** [comment]
@seanpkent Here's the original and yep, I exported as jpeg. 
![img_4930](https://cloud.githubusercontent.com/assets/175971/22074123/6874f206-dd4b-11e6-93c9-e28ab57aeca3.JPG)

**Comment by seanpkent** [comment]
@kimonostereo Thanks! I'll check it out.

**Comment by seanpkent** [comment]
@kimonostereo I've made some recent changes to the jpeg encoder which should fix this problem. I've tested with the image you sent me and I can export as a jpeg without any strange artifacts or pixelation. You should be seeing an update soon.

**Comment by kimonostereo** [comment]
Awesome! I look forward to trying it out!
