### ISSUE TITLE
Brush mask doesn't work

### ISSUE THREAD

**Issue by bonka** [Polarrco/polarr_mac_windows_support#53]
Brush mask doesn't work at all, neither in the Mac app, nor in the Photos extension. Tried on two different Macs. All the other filters work.

**Comment by bwang29** [comment]
Thanks for reporting this issue. It seems to be a bug, and we are fixing it soon.

**Comment by seanpkent** [comment]
@bonka The brush mask has been completely rewritten. It's faster and has more options to control size, flow and hardness. Expect an update soon!
