### ISSUE TITLE
Extension not showing up in Photos / Mac

### ISSUE THREAD

**Issue by d2hamilton** [Polarrco/polarr_mac_windows_support#56]
I saw that you had a problem with this last year, but I'm seeing it now. I purchased the "Lite" version and upgraded that to the full program which I had already purchased on my iPhone. I have just downloaded this (latest version) and I'm running the latest version of Sierra (10.12.3). When I run the program and then run Photos and / or look at the Extensions in Preferences there is nothing referring to Polarr. I have opened and closed Polarr and Photos many (many) times and rebooted the Mac. Is this a problem because I upgraded from the Lite version rather than paying for and downloading the pro version? I have still paid for the pro version, but I just went about it through the iOS version. 

Thanks

**Comment by bradycline** [comment]
I'm having the same issue. Purchased on iOS and then signed in on Mac to upgrade to pro. No extension available after launch/restart etc.

**Comment by bradycline** [comment]
Are others not experiencing this? I tried on a second Mac. Same problem. Either this is a serious bug or I'm not getting what I paid for. (Cross-platform was what got me to buy into Polarr instead of Affinity.)

**Comment by bradycline** [comment]
Any update on this?

**Comment by splodingsocks** [comment]
Same here.

**Comment by stlab21** [comment]
Downloaded lite version on Mac. Paid for pro version on Polarr web site. Able to sign in to Pro within Mac version but Mac App Store still asking to pay for pro version. Although Polarr app on Mac is signed in to the pro version, the App Store does not see it, therefore I cannot see the extensions in Photos. How does this get fixed so I can see the extensions in Photos?

**Comment by bwang29** [comment]
Lite version now has the extension since the previous update.
