### ISSUE TITLE
[Bug] EXIF Data lost on export

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_windows_support#59]
I have the option checked to preserve EXIF, but the editor goes ahead and wipes out data like date and time anyways. I really need the date and time to be correct as it was input so I don't have to correct it twice.

**Comment by seanpkent** [comment]
@kopaka7 This has been fixed recently. You should see an update soon!

**Comment by kopaka7** [comment]
@seanpkent Is this going to be applied retroactively? As in, when I export edited pictures again, will they now have EXIF data? If not I'm going to have to hold off on editing until I get the update.

**Comment by bwang29** [comment]
This should be fixed since last update.
