### ISSUE TITLE
Photo Access Delay

### ISSUE THREAD

**Issue by kopaka7** [Polarrco/polarr_mac_windows_support#62]
I just updated to the latest version, and I notice a long delay when opening a new picture from the filmstrip. Sometimes I can single click on a photo and it will open, other times if I don't double click, nothing registers. I'm assuming it should be single click to open because that's what we had before.

**Comment by seanpkent** [comment]
@kopaka7 I will investigate this. You definitely shouldn't have to double click to open a photo. When you single click, do you see 'loading photo' on the screen? The previous version covered the whole screen when loading a new photo, but the new version shows a smaller message display.

**Comment by kopaka7** [comment]
@seanpkent So it's interesting, after I changed the size of the filmstrip (which I didn't realize was possible) it seemed to happen less. When I restarted the app it is still not opening some pictures. The loading photo message doesn't come up when a single click is made, only a double click.

**Comment by seanpkent** [comment]
@kopaka7 That is interesting. I will definitely look into this.

**Comment by bwang29** [comment]
Issue resolved a long time ago, closing
