### ISSUE TITLE
Unloading saved files.

### ISSUE THREAD

**Issue by philiphavey** [Polarrco/polarr_mac_windows_support#71]
I received a file allotment full nag,  but I could find neither the instructions to dismiss files nor could I locate where the finds had accumulated.
I do a fair amount of graphics work and am quite ready to try out beta products if you do that sort of operation.

Phil Havey

**Comment by bwang29** [comment]
There is a tray in the bottom of the app you can pull up and then you can manage your photos here

![image](https://user-images.githubusercontent.com/806199/32809705-bbcb7c34-c94c-11e7-9b56-acad402e9ab8.png)
