### ISSUE TITLE
Automatic face detection didn't find any faces

### ISSUE THREAD

**Issue by FemmeFragile** [Polarrco/polarr_mac_windows_support#72]
Hello, I have a problem with Polarr... I'm using it on my notebook and on my computer. The problem is that on the notebook the face detection works, but on the computer it doesn't - the face is never found. I tried it also on the same photo and the result was different... Could you tell my why is this happening and how can I repair it?

Thank you so much!

**Comment by bwang29** [comment]
The next update is going to have much better face detection. Our apps have slightly different face detection engine for different versions.
