### ISSUE TITLE
[Bug] Visual trails around image

### ISSUE THREAD

**Issue by young-george** [Polarrco/polarr_mac_windows_support#73]
<img width="1015" alt="screen shot 2017-10-08 at 11 24 22 am" src="https://user-images.githubusercontent.com/16202746/31312295-8aed0586-ac1b-11e7-97a7-8e74635f7cd1.png">

As can be seen in the image above, trails are left across the interface. This occurs in Polarr app and Apple Photos extension.

Running Polarr 4.0.0 on macOS 10.13

**Comment by kopaka7** [comment]
Having the same issues. Guessing the app needs an update for High Sierra compatibility?

**Comment by bwang29** [comment]
We are updating soon for High Sierra. But this is a safari bug.
