### ISSUE TITLE
Problems with the "local adjustment"

### ISSUE THREAD

**Issue by tayo3** [Polarrco/polarr_mac_windows_support#76]
Hello, on the latest version 4.3., I have problem with the local adjustment (brush tool, radial mask...) it makes like on the next picture and the curser is blocked.

![capture d ecran 2017-11-17 a 10 21 10](https://user-images.githubusercontent.com/21297654/32940150-2754ac5a-cb82-11e7-96d3-12f2305cfcd1.jpg)

![capture d ecran 2017-11-17 a 10 22 11](https://user-images.githubusercontent.com/21297654/32940156-2c8c1d52-cb82-11e7-8cc4-9ebc6153041a.jpg)

**Comment by tayo3** [comment]
Any news ?

**Comment by bwang29** [comment]
Fixed in 4.4.0 on macOS app store.
